import type { Metadata } from 'next';
import Head from 'next/head';
import './globals.css';
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <script src="https://flackr.github.io/scroll-timeline/dist/scroll-timeline.js" async></script>
      </Head>
      <body
        className={ 'antialiased' }
      >
        { children }
      </body>
    </html>
  );
}
